# Generated by Django 6.0.6 on 2026-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0010_move_engine_models_to_core"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedinprofile",
            name="contribute_leads",
            field=models.BooleanField(default=True),
        ),
    ]
